services:
  db:
    image: mariadb:12.2-ubi
    container_name: mariadb_db
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      # Use a secure password in production!
      MARIADB_ROOT_PASSWORD: my_root_password
      MARIADB_DATABASE: todo
      MARIADB_USER: app_user
      MARIADB_PASSWORD: Password123!
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # Optional: Adminer to manage the database via browser
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mariadb_data: